### ISSUE TITLE
Version: 7.1.1 on Python 3.6: 'apt-smart -a' does not inform of updates

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [martin68/apt-smart#1]
Each of (1) `sudo apt-get update` and (2) `sudo apt-update` yields a message that some package(s) 'can be upgraded' if (and only if) some package(s) can in fact be upgraded. `apt-smart a` seems not to do that. Thus, any script that, in order to check for possible updates, parses the ouput of 1 or 2 will fail if your program is used instead. See e.g. [this snippet of bash](https://pastebin.com/0byuCiUK) that I wrote (or rather that I adapted so as to use apt-smart instead of apt).

**Comment by martin68** [comment]
@LinuxOnTheDesktop Thank you for using the tool, but you may be confused about the role of the tool.
I also got feedback from @Schlingnt at Reddit, the description in Readme is a little confusing. To make it clearer, I have pushed this commit:
https://github.com/martin68/apt-smart/commit/aca1108e7ba6f814a505d29d815071728156c406

> **Note: apt-smart is an APT helper tool rather than a replacement of apt/apt-get command,**
so in general apt-smart should not be run with sudo or as su. If apt-smart needs root privilege to continue (e.g. change sources.list), it will ask user to enter password.

So in your snippet of bash you can do `apt-smart -a` first, to auto-change mirror in sources.list, and then `sudo apt-get update` . Since most data are cached after `apt-smart -a`, the `sudo apt-get update` will be finished in very short time.

If you have any questions related to this, feel free to tell me. If you find the Readme is still confusing , just tell me how to make it better. Thanks again!

**Comment by LinuxOnTheDesktop** [comment]
Yes, I misunderstood. Thank you for the clarification. I suggest that you change the text that you quoted to the following, in order to be as clear as possible about how your program works. (I take the opportunity as well to polish the English.)

> **Note**. `apt-smart` is a _helper_ for the `apt` tool. It is not a _replacement_ for `apt` (or for `apt-get)`. So, `apt-smart` should _not_ be run _instead_ of either of those commands. Nor should `apt-smart` be run with `sudo` or via `su`; if `apt-smart` happens to need root privilege in order for it to continue (in order that it may, for example, change `sources.list`), then it will prompt for a password.
